# Generated by Django 3.2.9 on 2021-11-11 20:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todouser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='todouser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
