# Generated by Django 3.2.9 on 2021-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_auto_20211111_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='todouser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
